[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"
  
[build]
  publish = "dist"
  command = "pnpm run build"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    url = "https://anneleen.netlify.app"