[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "19"

[build]
  publish = "dist"
  command = "pnpm --filter ./app/ run build && nuxi build && cp _redirects dist/_redirects"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    url = "https://anneleen.netlify.app"
