version: 2.1

orbs:
  slack: circleci/slack@4.12.6

executors:
  pnpm-executor:
    docker:
      - image: node:21.6-browsers
    working_directory: /tmp/workspace

jobs:
  build:
    executor: pnpm-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: pnpm install --no-frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build app
          command: pnpm --filter ./app/ run build
      - run:
          name: Build main
          command: pnpm --filter ./ run build
      - run:
          name: Lint
          command: pnpm --filter ./app/ run lint
      - run:
          name: Test
          command: pnpm --filter ./app/ run coverage
      - slack/notify:
          channel: circleci
          event: always

workflows:
  flow:
    jobs:
      - build:
          context:
            - Slack
