[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"

[build]
  base = "app/"
  publish = "dist"
  command = "pnpm -w run app:build"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    url = "https://anneleen.netlify.app"
