# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: public/images
public_folder: /images

site_url: https://anneleen.netlify.app
show_preview_links: true

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'page'
    label: 'Page'
    folder: 'content/'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    preview_path: /{{slug}}
    sortable_fields: ['order', 'title']
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Order', name: 'order', widget: 'number' }
      - { label: 'Header Image', name: 'image.src', widget: 'image', media_folder: '/public/images/headers' }
      - { label: 'Highlight on homepage', name: 'highlight', widget: 'boolean' }
      - { label: 'Highlight image', name: 'highlightImg', widget: 'image', required: false, media_folder: '/public/images/highlights' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'news'
    label: 'News'
    folder: 'content/news'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    preview_path: /news/{{slug}}
    sortable_fields: ['date', 'title']
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Title Line 2', name: 'titleLine2', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Header Images', name: 'image.src', widget: 'image', media_folder: '/public/images/headers' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

