# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

#local_backend: true

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: /app/public/images
public_folder: /images

site_url: https://anneleen.netlify.app
show_preview_links: true

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'page'
    label: 'Page'
    folder: '/app/content/'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    preview_path: /{{slug}}
    sortable_fields: ['order', 'title', 'highlight']
    view_groups:
      - label: All
        field: all
      - label: Menu
        field: navigation
      - label: Highlight
        field: highlight
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Show in menu', name: 'navigation', widget: 'boolean', default: true }
      - { label: 'Order', name: 'order', widget: 'number' }
      - { label: 'Header Image', name: 'image.src', widget: 'image', required: false, media_folder: '/app/public/images/headers', choose_url: false }
      - { label: 'Highlight on homepage', name: 'highlight', widget: 'boolean' }
      - { label: 'Highlight image', name: 'highlightImg', widget: 'image', required: false, media_folder: '/app/public/images/highlights', choose_url: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'news'
    label: 'News'
    folder: '/app/content/news'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    preview_path: /news/{{slug}}
    sortable_fields: ['date', 'title']
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Title Line 2', name: 'titleLine2', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Summary', name: 'summary', widget: 'markdown' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image', required: true, media_folder: '/app/public/images/news/{{slug}}', choose_url: false }
      - { label: 'Header Image', name: 'image.src', widget: 'image', required: false, media_folder: '/app/public/images/headers', choose_url: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

